language: cpp
# command to install dependencies
sudo: required
dist: bionic
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libgtest-dev
            - g++-9
            - libc++-dev
            - libboost-all-dev
            - make
            - cmake
            - lcov
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-10
            - libboost-all-dev
            - libgtest-dev
            - libstdc++-10-dev
            - libc++-10-dev
            - libc++abi-10-dev
            - make
            - cmake
            - lcov
      env:
        - MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
before_install:
  - eval "${MATRIX_EVAL}"
install:
  - gem install coveralls-lcov
  - export CWD=$PWD
  - mkdir gtest
  - cp -r /usr/src/gtest/* gtest/
  - cd gtest
  - if [[ "$CXX" == *"clang++"* ]]; then
      cmake CMakeLists.txt -DCMAKE_CXX_FLAGS="$CXX_FLAGS -stdlib=libc++ -DGTEST_USE_OWN_TR1_TUPLE=1";
    else
      cmake CMakeLists.txt;
    fi
  - make
  - sudo cp *.* /usr/lib/
  - cd $CWD
script:
  - bash -e ./build_linux.sh
after_success:
  - if [[ "$CXX" == *"clang++"* ]]; then
      echo "clang++ place_holder";
    else
      echo "starting generate coverage report";
      lcov --directory ./build/ --capture --output-file --rc lcov_branch_coverage=1 ./coverage.info;
      lcov --remove ./coverage.info '/usr/*' '*/tests/*' --output-file ./coverage.info;
      lcov --list ./coverage.info;
      coveralls-lcov ./coverage.info;
    fi
  - echo "Job finished"
