language: cpp
# command to install dependencies
sudo: required
dist: bionic
compiler:
  - clang
  - gcc
os: linux
addons:
  apt:
    packages:
      - libgtest-dev
      - libc++-dev
      - libboost-all-dev
      - make
      - cmake
      - lcov
install:
  - gem install coveralls-lcov
  - export CWD=$PWD
  - mkdir gtest
  - cp -r /usr/src/gtest/* gtest/
  - cd gtest
  - if [[ "$CXX" == *"clang++"* ]]; then
      cmake CMakeLists.txt -DCMAKE_CXX_FLAGS="$CXX_FLAGS -stdlib=libc++ -DGTEST_USE_OWN_TR1_TUPLE=1";
    else
      cmake CMakeLists.txt;
    fi
  - make
  - sudo cp *.* /usr/lib/
  - cd $CWD
script:
  - bash ./build_linux.sh
after_success:
  - if [[ "$CXX" == *"g++"* ]]; then
      lcov --directory ./build/ --capture --output-file --rc lcov_branch_coverage=1 ./coverage.info;
      lcov --remove ./coverage.info '/usr/*' '*/tests/*' --output-file ./coverage.info;
      lcov --list ./coverage.info;
      coveralls-lcov ./coverage.info;
    else
      echo "clang++ place_holder";
    fi
  - echo "Job finished"
