name: CMake Linux build gcc-10
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup
        run: |
          sudo apt install -y g++-10 libboost-dev libgtest-dev libc++-dev make cmake
      - name: Prepare
        env:
          CXXFLAGS: -O2
          CC: gcc-10
          CXX: g++-10
        run: |
          sudo ln -sf /usr/bin/gcov-10 /usr/bin/gcov
          sudo ln -sf /usr/bin/gcov-10 /usr/bin/gcov
          wget http://mirrors.edge.kernel.org/ubuntu//pool/universe/l/lcov/lcov_1.14-2_all.deb
          sudo dpkg -i lcov_1.14-2_all.deb || sudo apt-get install -f -y
          export CWD=$PWD
          mkdir gtest
          cp -r /usr/src/gtest/* gtest/
          cd gtest
          cmake CMakeLists.txt
          make
          sudo cp *.* /usr/lib/
          cd $CWD
      - name: Compile
        env:
          CXXFLAGS: -O2
          CC: gcc-10
          CXX: g++-10
        run: |
          bash -e ./build_linux.sh
      - name: Coverage
        run: |
          echo "starting generate coverage report";
          mkdir ./coverage
          lcov --directory ./build/ --capture --output-file --rc lcov_branch_coverage=1 ./coverage/lcov.info
          lcov --remove ./coverage/lcov.info '/usr/*' '*/tests/*' --output-file ./coverage/lcov.info
          lcov --list ./coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}